DROP TABLE IF EXISTS files CASCADE;
DROP TABLE IF EXISTS folders;

CREATE TABLE folders (
  id SERIAL PRIMARY KEY,
  name  TEXT UNIQUE NOT NULL
);

CREATE TABLE files (
  id SERIAL PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  size INT NOT NULL,
  folder_id INT NOT NULL REFERENCES folders(id) ON DELETE CASCADE
);